name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan deploy.jakelazaroff.com >> ~/.ssh/known_hosts
          echo "Host deploy.jakelazaroff.com
            IdentityFile ~/.ssh/deploy_key
            IdentitiesOnly yes" >> ~/.ssh/config
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        run: |
          git remote add deploy deploy@deploy.jakelazaroff.com:/srv/deploy/til/repo.git
          git push deploy main
